# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e0821839e29c7648a55ece42cf5046cb"
name = "bundle-app"
application_url = "https://buys-marvel-observed-ghz.trycloudflare.com"
embedded = true
handle = "bundle-app-235"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app_subscriptions_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,read_price_rules,read_products,read_themes,write_discounts,write_files,write_price_rules,write_products,write_themes"

[auth]
redirect_urls = [
  "https://buys-marvel-observed-ghz.trycloudflare.com/auth/callback",
  "https://buys-marvel-observed-ghz.trycloudflare.com/auth/shopify/callback",
  "https://buys-marvel-observed-ghz.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://store-revive.myshopify.com/apps/bundles"
subpath = "bundles"
prefix = "apps"

[pos]
embedded = false
